### ISSUE TITLE
Lock in the write API

### ISSUE THREAD

**Issue by Narvalex** [dasiths/NEventLite#1]
Why use a lock in the writing method or the repository? This will harm performance AFAIK
https://github.com/dasiths/EventSourcingDemo/blob/master/EventSourcingDemo/Repository/Repository.cs

**Comment by dasiths** [comment]
To ensure If the Repo commit part will be synchronized and thread safe. Just a good pattern AFAIK when implementing a repo commit or unit of work.

**Comment by Narvalex** [comment]
Sync with what? The whole EventStore database is lock free! Not a good pattern at all if not strictly necesary AFAIK.
The commit API in the Event Store client has a concurrency check parameter. I think is better to let the database do the concurrency check work. Greg Young and his team worked hard to make the database engine lockless

**Comment by dasiths** [comment]
EventStore might be lock free but the Repository is not thread safe. I was just wary of two threads calling Save() on the same repo. See the repo implementation here: http://www.codeproject.com/Articles/555855/Introduction-to-CQRS

You are right. I agree that locks reduce performance. At best I should have explained and made that part optional.

**Comment by Narvalex** [comment]
Take a look at this. It is my own implementation. Is lock free. The Event Store does the heavy lifting. And it is thread safe. This is not a relational database. 
https://github.com/Narvalex/Eventing/blob/release-v.1.0.0/src/Eventing/EventSourcing/EventSourcedRepository.cs

**Comment by dasiths** [comment]
Will have a look thanks. Like I said EventStore is not the reason a lock was needed. It was to make it thread safe.

**Comment by Narvalex** [comment]
Can you check this pull request please? Pull request #3 As you said, I made the lock optional. Not sure is there a prettier API

**Comment by dasiths** [comment]
Will do. Cheers.

**Comment by dasiths** [comment]
Marking this as resolved
