### ISSUE TITLE
Compare with other Event Store implementations 

### ISSUE THREAD

**Issue by MNF** [dasiths/NEventLite#7]
There are a few other .net packages that implemented Event Store. It will be useful in readme.md to see what are advantages( and disadvantages) of this library compare to other packages, such as EventStore .net Client API https://github.com/EventStore/EventStore and 
https://github.com/SQLStreamStore/SQLStreamStore. 

The author of SQLStreamStore answered to  similar question at 
https://github.com/SQLStreamStore/SQLStreamStore/issues/108#issuecomment-348154346

**Comment by dasiths** [comment]
@MNF NEventLite is a library that aims to solve the problem of managing the aggregate lifecycle. It can support many event store providers. NEventLite provides you a couple of interfaces, once implemented can work with any provider. See the providers we already have. https://github.com/dasiths/NEventLite/tree/master/src/Storage. More will be added.
