### ISSUE TITLE
Intermittent Failure in ReflectionHelper.FindEventHandlerMethodsInAggregate

### ISSUE THREAD

**Issue by ltdavids** [dasiths/NEventLite#8]
I have run into an issue where the FindEventHandlerMethodsInAggregate method in ReflectionHelper fails intermittently.  I have not been able to chase it down exactly but it seems it could be a threading issue.  If I avoid throwing the exception if the dictionary for the Aggregate has already been added (see below), it seems to fix the issue.  Thoughts?
```
if (AggregateEventHandlerCache.TryAdd(aggregateType, eventHandlers) == false 
    && AggregateEventHandlerCache.ContainsKey(aggregateType) == false)
{
    throw new System.Exception($"Error registering methods for handling events in {aggregateType.Name}");
}
```

**Comment by dasiths** [comment]
@ltdavids cheers for raising the issue.
I'm working on the next version of NEventLite here https://github.com/dasiths/NEventLite/tree/master/vNext/src

It's very raw but I'll invetigate your issue further in there.

**Comment by dasiths** [comment]
I'll go with `AggregateEventHandlerCache.GetOrAdd(aggregateType, eventHandlers);` to fix this
